'use strict';

var minify = (function() {
var minify = require('html-minifier').minify;
return function(value, options, callback, errorback) {
  options.log = function(message) {
    console.log(message);
  };
  var minified;
  try {
    minified = minify(value, options);
  }
  catch (err) {
    return errorback(err);
  }
  callback(minified);
};
})();
if (typeof Worker === 'function') {
var worker = new Worker('assets/worker.js');
worker.onmessage = function() {
  minify = function(value, options, callback, errorback) {
    worker.onmessage = function(event) {
      var data = event.data;
      if (data.error) {
        errorback(data.error);
      }
      else {
        callback(data);
      }
    };
    worker.postMessage({
      value: value,
      options: options
    });
  };
};
}

function byId(id) {
  return document.getElementById(id);
}

function escapeHTML(str) {
return (str + '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function getOptions() {
var options = {
  "caseSensitive":false,
  "collapseBooleanAttributes":true,
  "collapseInlineTagWhitespace":false,
  "collapseWhitespace":true,
  "conservativeCollapse":false,
  "decodeEntities":true,
  "html5":true,
  "includeAutoGeneratedTags":false,
  "keepClosingSlash":false,
  "minifyCSS":true,
  "minifyJS":true,
  "preserveLineBreaks":false,
  "preventAttributesEscaping":false,
  "processConditionalComments":true,
  "processScripts":["text/html"],
  "removeAttributeQuotes":true,
  "removeComments":true,
  "removeEmptyAttributes":true,
  "removeEmptyElements":false,
  "removeOptionalTags":false,
  "removeRedundantAttributes":true,
  "removeScriptTypeAttributes":true,
  "removeStyleLinkTypeAttributes":true,
  "removeTagWhitespace":false,
  "sortAttributes":true,
  "sortClassName":true,
  "trimCustomFragments":true,
  "useShortDoctype":false
}
return options;
}

function commify(str) {
return String(str)
  .split('').reverse().join('')
  .replace(/(...)(?!$)/g, '$1,')
  .split('').reverse().join('');
}



var defaultOptions = getOptions();